language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install . --use-mirrors"
  - "pip install -r dev-requirements.txt --use-mirrors"
# command to run tests
script: py.test tests
